# Generated by Django 3.1.3 on 2020-11-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201105_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='created_at',
        ),
    ]
